*** ch14-03-exclusive-or-mb — memberships are ignored during variant generation (used only for least-sort computation) (Maude manual §14.4)

fmod EXCLUSIVE-OR-MB is
 sorts Nat NatSet .
 op 0 : -> Nat [ctor] .
 op s : Nat -> Nat [ctor] .

 subsort Nat < NatSet .
 op mt : -> NatSet [ctor] .
 op _*_ : NatSet NatSet -> NatSet [ctor assoc comm] .

 sort Empty .
 subsort Empty < NatSet .
 mb mt : Empty .

 vars X Y Z : [NatSet] .
 eq [idem] :    X * X = mt   [variant] .
 eq [idem-Coh] : X * X * Z = Z [variant] .
 eq [id] :      X * mt = X   [variant] .
endfm

*** §14.4: 2 variants; the mb is not used to instantiate variables to mt
get irredundant variants in EXCLUSIVE-OR-MB : X:Empty * Y:Empty .
