set show timing off .
fmod EXCLUSIVE-OR-P19 is
  sorts Elem ElemXor .
  subsort Elem < ElemXor .
  ops a b c : -> Elem .
  op mt : -> ElemXor .
  op _*_ : ElemXor ElemXor -> ElemXor [assoc comm] .
  vars X Y Z : [ElemXor] .
  vars V1 V2 V3 : [ElemXor] .
  eq [idem] : X * X = mt [variant] .
  eq [idem-Coh] : X * X * Z = Z [variant] .
  eq [id] : X * mt = X [variant] .
  op f1 : [ElemXor] -> [ElemXor] .
endfm
variant unify f1(a) * f1(V1) =? f1(V2 * b) * f1(V3 * c) .
filtered variant unify f1(a) * f1(V1) =? f1(V2 * b) * f1(V3 * c) .
