*** PRELUDE
*** C3e-oo-rename-views — OO renaming items (class/attr/msg to) over an omod
omod FOO is
  sort Val .
  ops v0 v1 : -> Val [ctor] .
  class Foo | a : Val .
  msg m : Oid Val -> Msg .
  op o : -> Oid [ctor] .
  op getval : Object -> Val .
  var O : Oid .
  var V : Val .
  eq getval(< O : Foo | a : V >) = V .
endom
mod BAR is
  including FOO * (class Foo to Bar, attr a to b, msg m to n) .
endm
reduce in BAR : getval(< o : Bar | b : v1 >) .
